apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.env.DATABASE_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.DATABASE_PASSWORD | b64enc }}
