apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.fullname" . }}-keyfile
  labels:
    app: {{ include "mongo.name" . }}
    chart: {{ include "mongo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mongo-keyfile: {{ .Files.Get "secrets/mongo-keyfile" | b64enc }}
