apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
