apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secret
type: Opaque
data:
  MONGO_USER: {{ .Values.env.DATABASE_USER | b64enc }}
  MONGO_PASSWORD: {{ .Values.env.DATABASE_PASSWORD | b64enc }}
