replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "8.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  
securityContext: {}

containers:
  - name: mongo-db-0
    port: 27017
    volume: mongo-vol-0
  - name: mongo-db-1
    port: 27018
    volume: mongo-vol-1
  - name: mongo-db-2
    port: 27019
    volume: mongo-vol-2

volumes:
  - name: mongo-vol-0
    path: /run/desktop/mnt/host/c/tmp/mongo1
  - name: mongo-vol-1
    path: /run/desktop/mnt/host/c/tmp/mongo2
  - name: mongo-vol-2
    path: /run/desktop/mnt/host/c/tmp/mongo3

service:  
  type: None
  port: 27017
  targetPort: 27017
# service:  
#   type: ClusterIP
#   port: 27017
#   targetPort: 27017

ingress:
  enabled: false
  className: ""
  annotations: {}
    
  hosts:
    - host: mongo.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  
resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "mongosauser"

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
livenessProbe:
  exec:
    command: ["mongosh", "--eval", "db.runCommand('ping').ok"]
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  exec:
    command: ["mongosh", "--eval", "db.runCommand('ping').ok"]
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  size: 1Gi
  storageClassName: "hostpath"

replicaSetName: rs0
auth:
  enabled: false
  keyFilePath: /etc/secrets/mongo-keyfile


env:
  DATEBASE_NAME: "dev"
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "adminpassword"
  REPLICA_SET_KEY: "replicaSetKey123"

